version: "3.9"

networks:
  alireaza:
    name: ${NETWORK_NAME:-alireaza}
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${NETWORK_IPV4_SUBNET:-172.110.0.0/24}
          gateway: ${NETWORK_IPV4:-172.110.0.1}
    driver_opts:
      com.docker.network.bridge.name: ${NETWORK_BRIDGE_NAME:-alireaza}

services:
  nginx:
    build: ./nginx
    volumes:
      - ./src:/var/www/html
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/log:/var/log/nginx
    restart: ${NGINX_RESTART_POLICY:-always}
    networks:
      alireaza:
        ipv4_address: ${NGINX_IPV4:-172.110.0.2}

  php:
    build: ./php
    volumes:
      - ./src:/var/www/html
      - ./php/conf.d:/usr/local/etc/php/conf.d
      - ./php/udocker:/home/udocker
    restart: ${PHP_RESTART_POLICY:-always}
    environment:
      - PHP_OPCACHE_JIT=${PHP_OPCACHE_JIT:-on}
      - PHP_XDEBUG_MODE=${PHP_XDEBUG_MODE:-off}
    user: ${CURRENT_UID:-root}
    networks:
      alireaza:
        ipv4_address: ${PHP_IPV4:-172.110.0.3}
